export type PropertyType = "venta" | "alquiler";
export type PropertyStatus = "activa" | "pausada" | "destacada";

export interface Property {
  id: string;
  title: string;
  slug: string;
  price: number;
  currency: "DOP" | "USD";
  type: PropertyType;
  category: string;
  city: string;
  zone: string;
  beds: number;
  baths: number;
  areaM2: number;
  verified: boolean;
  featured: boolean;
  /** Patrocinio pago: carrusel promocional en inicio */
  promo?: boolean;
  image: string;
  images: string[];
  lat: number;
  lng: number;
  amenities: string[];
  description: string;
}

function img(seed: string, w: 1200 | 800 = 1200): string {
  return `https://picsum.photos/seed/${seed}/${w}/800`;
}

function gallery(
  main: string,
  a: string,
  b: string,
  c: string,
  d: string
): string[] {
  return [img(main, 1200), img(a, 800), img(b, 800), img(c, 800), img(d, 800)];
}

// Unsplash real estate image URLs for reliable property images
const unsplashImages: Record<string, string> = {
  modern_house_1: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop",
  modern_house_2: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
  luxury_villa: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
  apartment_1: "https://images.unsplash.com/photo-1600585154084-4e5fe7c39198?w=800&h=600&fit=crop",
  apartment_2: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
  penthouse: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop",
  townhouse: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
  loft: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
  property_1: "https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800&h=600&fit=crop",
  property_2: "https://images.unsplash.com/photo-1600566753476-8aa80a578004?w=800&h=600&fit=crop",
  property_3: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
  property_4: "https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=800&h=600&fit=crop",
  property_5: "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&h=600&fit=crop",
  property_6: "https://images.unsplash.com/photo-1600573472591-9b3b24601c27?w=800&h=600&fit=crop",
  property_7: "https://images.unsplash.com/photo-1600585152915-d0bec9a8d369?w=800&h=600&fit=crop",
  property_8: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&h=600&fit=crop",
  property_9: "https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=800&h=600&fit=crop",
  property_10: "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&h=600&fit=crop",
  land_1: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop",
  land_2: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop",
  land_3: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&h=600&fit=crop",
  land_4: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=600&fit=crop",
  land_5: "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=800&h=600&fit=crop",
  interior_1: "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&h=600&fit=crop",
  interior_2: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&h=600&fit=crop",
  interior_3: "https://images.unsplash.com/photo-1600566753476-8aa80a578004?w=800&h=600&fit=crop",
  interior_4: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
  interior_5: "https://images.unsplash.com/photo-1600210491892-03d5407fa87?w=800&h=600&fit=crop",
  commercial_1: "https://images.unsplash.com/photo-1486403099049-887da5d23fe5?w=800&h=600&fit=crop",
  commercial_2: "https://images.unsplash.com/photo-1497366811353-3870884e606f?w=800&h=600&fit=crop",
  commercial_3: "https://images.unsplash.com/photo-1449844908841-aa7e82bbb350?w=800&h=600&fit=crop",
  commercial_4: "https://images.unsplash.com/photo-1497215843000-955c57177f1c?w=800&h=600&fit=crop",
  office_1: "https://images.unsplash.com/photo-1497366811353-3870884e606f?w=800&h=600&fit=crop",
  office_2: "https://images.unsplash.com/photo-1504384308090-c894fdcc1d34?w=800&h=600&fit=crop",
  office_3: "https://images.unsplash.com/photo-1524750919432-9391c09a52a1?w=800&h=600&fit=crop",
  office_4: "https://images.unsplash.com/photo-1517245385007-15d4d07b59dd?w=800&h=600&fit=crop",
  office_5: "https://images.unsplash.com/photo-1497215843000-955c57177f1c?w=800&h=600&fit=crop",
  farm_1: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop",
  farm_2: "https://images.unsplash.com/photo-1558618666-fcd25c85f81e?w=800&h=600&fit=crop",
  hotel_1: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop",
  hotel_2: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=600&fit=crop",
  beach_house: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&h=600&fit=crop",
  estate_1: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
  estate_2: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
  garden_1: "https://images.unsplash.com/photo-1558618666-fcd25c85f81e?w=800&h=600&fit=crop",
  garden_2: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=600&fit=crop",
  street_1: "https://images.unsplash.com/photo-1449844908841-aa7e82bbb350?w=800&h=600&fit=crop",
  colonial: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=600&fit=crop",
  pool_villa: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
  swimming_pool: "https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=800&h=600&fit=crop",
  // Additional images for new properties
  modern_ext_1: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&h=600&fit=crop",
  modern_ext_2: "https://images.unsplash.com/photo-1588854337443-2b755b1bac37?w=800&h=600&fit=crop",
  modern_ext_3: "https://images.unsplash.com/photo-1600585152915-d0bec9a8d369?w=800&h=600&fit=crop",
  modern_ext_4: "https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800&h=600&fit=crop",
  modern_ext_5: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
  luxury_int_1: "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&h=600&fit=crop",
  luxury_int_2: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&h=600&fit=crop",
  luxury_int_3: "https://images.unsplash.com/photo-1600566753476-8aa80a578004?w=800&h=600&fit=crop",
  luxury_int_4: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
  luxury_int_5: "https://images.unsplash.com/photo-1600210491892-03d5407fa87?w=800&h=600&fit=crop",
  tropical_1: "https://images.unsplash.com/photo-1510009489794-3b2226a7a973?w=800&h=600&fit=crop",
  tropical_2: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop",
  tropical_3: "https://images.unsplash.com/photo-1559827633-8e84bfe9a80c?w=800&h=600&fit=crop",
  mountain_1: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop",
  mountain_2: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&h=600&fit=crop",
  mountain_3: "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=800&h=600&fit=crop",
  condo_1: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop",
  condo_2: "https://images.unsplash.com/photo-1549190771-d68u9e3d2c59?w=800&h=600&fit=crop",
  condo_3: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e9?w=800&h=600&fit=crop",
  condo_4: "https://images.unsplash.com/photo-1574362848147-ef7758a6f3b?w=800&h=600&fit=crop",
  condo_5: "https://images.unsplash.com/photo-1585320804297-20cf2c57a9e6?w=800&h=600&fit=crop",
  warehouse_1: "https://images.unsplash.com/photo-1586528176730-6d6647f5b2b6?w=800&h=600&fit=crop",
  warehouse_2: "https://images.unsplash.com/photo-1559289809-1952e543e6e8?w=800&h=600&fit=crop",
  garden_view_1: "https://images.unsplash.com/photo-1588058492774-38bfe2e8c9b1?w=800&h=600&fit=crop",
  garden_view_2: "https://images.unsplash.com/photo-1600566753476-8aa80a578004?w=800&h=600&fit=crop",
  garden_view_3: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
  kitchen_1: "https://images.unsplash.com/photo-1556909114-f6e6f1625b72?w=800&h=600&fit=crop",
  kitchen_2: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&h=600&fit=crop",
  bathroom_1: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&h=600&fit=crop",
  bathroom_2: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&h=600&fit=crop",
};

function getUnsplash(key: string): string {
  return unsplashImages[key] || `https://picsum.photos/seed/${key}/800/600`;
}

export const MOCK_PROPERTIES: Property[] = [
  // === PROPIEDADES DE VENTA - LUXURY ===

  {
    id: "1",
    title: "Penthouse con vista al mar — Piantini",
    slug: "penthouse-piantini",
    price: 285000,
    currency: "USD",
    type: "venta",
    category: "Penthouse",
    city: "Santo Domingo",
    zone: "Piantini",
    beds: 4,
    baths: 3,
    areaM2: 220,
    verified: true,
    featured: true,
    promo: true,
    image: getUnsplash("modern_house_2"),
    images: [
      getUnsplash("modern_house_2"),
      getUnsplash("luxury_villa"),
      getUnsplash("apartment_2"),
      getUnsplash("penthouse"),
      getUnsplash("property_1"),
    ],
    lat: 18.4737,
    lng: -69.9294,
    amenities: [
      "parking",
      "gym",
      "pool",
      "security",
      "elevator",
      "terrace",
      "concierge",
      "ocean-view",
    ],
    description:
      "Exclusivo penthouse de 220 m² con acabados premium importados, terraza privada de 45 m² con jacuzzi y vista panorámica 360° del mar Caribe y el valle de Piantini. Cocina italiana con isla en mármol Calacatta, sistema domótico integrado, 4 suites con walk-in closet y ascensor privado directo desde el estacionamiento subterráneo de 2 espacios.",
  },
  {
    id: "2",
    title: "Villa moderna en Casa de Campo",
    slug: "villa-casa-de-campo",
    price: 1250000,
    currency: "USD",
    type: "venta",
    category: "Villa",
    city: "La Romana",
    zone: "Casa de Campo",
    beds: 6,
    baths: 5,
    areaM2: 480,
    verified: true,
    featured: true,
    promo: true,
    image: getUnsplash("luxury_villa"),
    images: [
      getUnsplash("luxury_villa"),
      getUnsplash("property_3"),
      getUnsplash("loft"),
      getUnsplash("property_2"),
      getUnsplash("property_4"),
    ],
    lat: 18.4274,
    lng: -68.9028,
    amenities: ["pool", "garden", "security", "parking", "terrace", "gym", "golf", "marina"],
    description:
      "Majestuosa villa contemporánea de 480 m² con piscina infinita bordeante, jardín tropical diseñado por paisajistas italianos y acceso privado al golf y marina de Casa de Campo. 6 suites con terraza al jardín, bodega climatificada para vinos, cine privado de 8 asientos, gimnasio equipado con Technogym y sistema de seguridad con cámaras térmicas 24/7. Construcción certificada LEED.",
  },
  {
    id: "8",
    title: "Villa frente al mar en Cap Cana",
    slug: "villa-cap-cana",
    price: 2390000,
    currency: "USD",
    type: "venta",
    category: "Villa",
    city: "Punta Cana",
    zone: "Cap Cana",
    beds: 5,
    baths: 5,
    areaM2: 520,
    verified: true,
    featured: true,
    promo: true,
    image: getUnsplash("property_3"),
    images: [
      getUnsplash("property_3"),
      getUnsplash("luxury_villa"),
      getUnsplash("loft"),
      getUnsplash("property_2"),
      getUnsplash("modern_house_2"),
    ],
    lat: 18.5004,
    lng: -68.4042,
    amenities: [
      "pool",
      "garden",
      "parking",
      "security",
      "ocean-view",
      "beach-access",
      "golf",
      "marina",
    ],
    description:
      "Residencia signature de Cap Cana con acceso directo a playa virgen de arena dorada. 520 m² de arquitectura bioclimática con muros de vidrio panorámicos, techos voladizo de hormigón pulido y piscina de olas con sumidero. Muelle privado opcional para yates hasta 40 pies. Domótica Crestron, paneles solares de última generación, generador de respaldo de 20 kVA y spa con sauna seca y vapor.",
  },
  {
    id: "13",
    title: "Penthouse sky lounge — Cabeza de Toro",
    slug: "penthouse-cabeza-toro",
    price: 890000,
    currency: "USD",
    type: "venta",
    category: "Penthouse",
    city: "Punta Cana",
    zone: "Cabeza de Toro",
    beds: 3,
    baths: 3,
    areaM2: 240,
    verified: true,
    featured: true,
    promo: true,
    image: getUnsplash("loft"),
    images: [
      getUnsplash("loft"),
      getUnsplash("modern_house_2"),
      getUnsplash("luxury_villa"),
      getUnsplash("apartment_2"),
      getUnsplash("penthouse"),
    ],
    lat: 18.4829,
    lng: -68.3588,
    amenities: ["pool", "gym", "terrace", "security", "elevator", "spa", "concierge"],
    description:
      "Penthouse de diseño autor con sky lounge privado de 80 m² en la azotea, equipado con cocina de chef, barra de cócteles y hamacas panorámicas. 3 suites con baños de mármol statuario, domótica Lutron y acabados importados de Italia y España. Piscina desbordante privada, gimnasio con vista al mar y acceso exclusivo a las playas de Cabeza de Toro.",
  },
  {
    id: "20",
    title: "Villa mediterránea — Costámbar",
    slug: "villa-costambar",
    price: 575000,
    currency: "USD",
    type: "venta",
    category: "Villa",
    city: "Puerto Plata",
    zone: "Costámbar",
    beds: 4,
    baths: 4,
    areaM2: 310,
    verified: true,
    featured: false,
    promo: true,
    image: getUnsplash("property_4"),
    images: [
      getUnsplash("property_4"),
      getUnsplash("luxury_villa"),
      getUnsplash("property_3"),
      getUnsplash("modern_house_2"),
      getUnsplash("loft"),
    ],
    lat: 19.7668,
    lng: -70.6984,
    amenities: ["pool", "garden", "parking", "security", "ocean-view", "solar"],
    description:
      "Residencia unifamiliar de estilo mediterráneo con paneles solares y generador de respaldo. 310 m² distribuidos en dos niveles con patio central andaluz, fuente de azulejos artesanales y porche perimetral. Cocina gourmet con campana de cobre italiana, 4 habitaciones con closets empotrados, piscina climatificada con iluminación LED y sistema de cloración salina.",
  },
  {
    id: "26",
    title: "Barahona cliff villa — vista Caribe",
    slug: "villa-barahona",
    price: 410000,
    currency: "USD",
    type: "venta",
    category: "Villa",
    city: "Barahona",
    zone: "Paraíso",
    beds: 4,
    baths: 3,
    areaM2: 260,
    verified: false,
    featured: false,
    image: getUnsplash("land_2"),
    images: [
      getUnsplash("land_2"),
      getUnsplash("land_3"),
      getUnsplash("land_5"),
      getUnsplash("land_4"),
      getUnsplash("land_1"),
    ],
    lat: 18.2089,
    lng: -71.0887,
    amenities: ["pool", "terrace", "ocean-view", "parking", "solar"],
    description:
      "Arquitectura orgánica sobre acantilado con brisa constante y acceso a cala privada. 260 m² de diseño sustentable con muros de piedra natural, pisos de micro-topping y techos de madera de pino. 4 habitaciones con vista al mar Caribe, piscina de diseño natural con zona de buceo, cocina orgánica con huerto elevado y sistema de captación de agua pluvial.",
  },

  // === PROPIEDADES DE VENTA - RESIDENCIAL ===

  {
    id: "3",
    title: "Apartamento ejecutivo Naco",
    slug: "apto-naco",
    price: 3200,
    currency: "USD",
    type: "alquiler",
    category: "Apartamento",
    city: "Santo Domingo",
    zone: "Naco",
    beds: 3,
    baths: 2,
    areaM2: 145,
    verified: true,
    featured: false,
    image: getUnsplash("apartment_1"),
    images: [
      getUnsplash("apartment_1"),
      getUnsplash("property_8"),
      getUnsplash("property_6"),
      getUnsplash("property_7"),
      getUnsplash("property_5"),
    ],
    lat: 18.4655,
    lng: -69.9312,
    amenities: ["parking", "elevator", "security", "gym", "wifi", "ac", "furnished"],
    description:
      "Apartamento ejecutivo de 145 m² completamente amueblado con diseño contemporáneo. Ubicado en torre premium del sector Naco, a pasos de los mejores restaurantes, centros comerciales y espacios de coworking. Incluye 3 habitaciones, 2 baños completos, cocina integral con electrodomésticos Samsung, sala con chimenea eléctrica y balcón con vista al jardín del complejo. Estacionamiento techado para 2 vehículos.",
  },
  {
    id: "4",
    title: "Townhouse en Punta Cana Village",
    slug: "townhouse-punta-cana",
    price: 410000,
    currency: "USD",
    type: "venta",
    category: "Townhouse",
    city: "Punta Cana",
    zone: "Punta Cana Village",
    beds: 3,
    baths: 3,
    areaM2: 190,
    verified: false,
    featured: false,
    image: getUnsplash("townhouse"),
    images: [
      getUnsplash("townhouse"),
      getUnsplash("modern_house_2"),
      getUnsplash("property_9"),
      getUnsplash("property_10"),
      getUnsplash("property_3"),
    ],
    lat: 18.5601,
    lng: -68.3725,
    amenities: ["pool", "garden", "parking", "security", "beach-access"],
    description:
      "Townhouse de tres niveles con jardín privado y piscina compartida en el exclusivo desarrollo Punta Cana Village. 190 m² con distribución inteligente: planta baja con sala-comedor y cocina abierta, primer nivel con master suite y segunda habitación, tercer nivel con terraza solarium. A minutos de playas de arena blanca y del aeropuerto Internacional de La Romana.",
  },
  {
    id: "5",
    title: "Loft industrial en Zona Colonial",
    slug: "loft-zona-colonial",
    price: 185000,
    currency: "USD",
    type: "venta",
    category: "Loft",
    city: "Santo Domingo",
    zone: "Ciudad Colonial",
    beds: 2,
    baths: 2,
    areaM2: 110,
    verified: true,
    featured: false,
    image: getUnsplash("loft"),
    images: [
      getUnsplash("loft"),
      getUnsplash("apartment_1"),
      getUnsplash("property_5"),
      getUnsplash("property_7"),
      getUnsplash("property_1"),
    ],
    lat: 18.4733,
    lng: -69.8828,
    amenities: ["terrace", "elevator", "security", "wifi", "balcony"],
    description:
      "Loft de 110 m² con techos de 4.5 metros de altura, vigas de madera expuestas y amplios ventanales que inundan el espacio con luz natural. Acabados de estética industrial refinada: pisos de concreto pulido, paredes de ladrillo visto y metal negro. Terraza privada de 20 m² con vista a las coloniales calles empedradas. A pasos del Ateneo, galerías de arte y cafés culturales.",
  },
  {
    id: "12",
    title: "Apartamento vista mar — Playa Dorada",
    slug: "apto-playa-dorada",
    price: 195000,
    currency: "USD",
    type: "venta",
    category: "Apartamento",
    city: "Puerto Plata",
    zone: "Playa Dorada",
    beds: 2,
    baths: 2,
    areaM2: 98,
    verified: false,
    featured: false,
    image: getUnsplash("interior_3"),
    images: [
      getUnsplash("interior_3"),
      getUnsplash("interior_2"),
      getUnsplash("interior_4"),
      getUnsplash("interior_5"),
      getUnsplash("interior_1"),
    ],
    lat: 19.7586,
    lng: -70.7261,
    amenities: ["pool", "parking", "security", "ocean-view", "wifi", "balcony"],
    description:
      "Torre con acceso a playa, ideal inversión vacacional o Airbnb regulado. 98 m² con vista panorámica al mar Caribe desde el balcón. Cocina equipada con electrodomésticos de acero inoxidable, pisos porcelanato pulido y aire acondicionado central en todas las habitaciones. El complejo cuenta con piscina olímpica, restaurante, gimnasio y acceso directo a la playa.",
  },
  {
    id: "19",
    title: "Apartamento nuevo — Ciudad Juan Bosch",
    slug: "apto-ciudad-juan-bosch",
    price: 118000,
    currency: "USD",
    type: "venta",
    category: "Apartamento",
    city: "Santo Domingo Este",
    zone: "Ciudad Juan Bosch",
    beds: 3,
    baths: 2,
    areaM2: 105,
    verified: true,
    featured: false,
    image: getUnsplash("property_2"),
    images: [
      getUnsplash("property_2"),
      getUnsplash("apartment_1"),
      getUnsplash("property_5"),
      getUnsplash("property_8"),
      getUnsplash("property_6"),
    ],
    lat: 18.5021,
    lng: -69.8425,
    amenities: ["pool", "gym", "parking", "security", "elevator", "pet-friendly"],
    description:
      "Proyecto cerrado con áreas sociales, circuito cerrado y parque infantil. 105 m² de departamento moderno con distribución funcional: sala-comedor independiente, cocina semi-equipada con despensa, 3 habitaciones con closets y 2 baños completos. Ventanas de vidrio templado con aislamiento acústico. El complejo incluye piscina para adultos, gimnasio equipado y zonas verdes para niños.",
  },
  {
    id: "22",
    title: "Townhouse familiar — Alma Rosa",
    slug: "townhouse-alma-rosa",
    price: 225000,
    currency: "USD",
    type: "venta",
    category: "Townhouse",
    city: "Santo Domingo Este",
    zone: "Alma Rosa",
    beds: 3,
    baths: 2,
    areaM2: 155,
    verified: true,
    featured: false,
    image: getUnsplash("property_9"),
    images: [
      getUnsplash("property_9"),
      getUnsplash("property_10"),
      getUnsplash("luxury_villa"),
      getUnsplash("apartment_2"),
      getUnsplash("apartment_1"),
    ],
    lat: 18.4892,
    lng: -69.8544,
    amenities: ["parking", "garden", "security", "pet-friendly", "storage"],
    description:
      "Conjunto cerrado con vigilancia, patio trasero y cuarto de servicio. 155 m² en townhouse de tres plantas: planta baja con sala de estar y comedor, primer piso con cocina integrada, dos habitaciones y baño completo, segundo piso con terraza y master suite. Estacionamiento techado para un vehículo y bodega individual. Ideal para familias que buscan seguridad y comodidad.",
  },
  {
    id: "30",
    title: "Casa moderna con piscina — Los Jardines de Arroyo Hondo",
    slug: "casa-arroyo-hondo",
    price: 385000,
    currency: "USD",
    type: "venta",
    category: "Casa",
    city: "Santo Domingo",
    zone: "Arroyo Hondo",
    beds: 4,
    baths: 3,
    areaM2: 280,
    verified: true,
    featured: false,
    image: getUnsplash("modern_ext_1"),
    images: [
      getUnsplash("modern_ext_1"),
      getUnsplash("modern_ext_2"),
      getUnsplash("luxury_int_1"),
      getUnsplash("luxury_int_2"),
      getUnsplash("property_7"),
    ],
    lat: 18.4203,
    lng: -69.9756,
    amenities: ["pool", "garden", "parking", "security", "terrace", "ac"],
    description:
      "Residencia moderna de dos plantas con piscina climatificada y jardín paisajístico. 280 m² con líneas minimalistas, amplios ventanales de piso a techo y pisos de porcelanato italiano. 4 habitaciones, master suite con jacuzzi y walk-in closet. Cocina con isla en cuarzo blanco, electrodomésticos Sub-Zero y Wolf. Sistema solar térmico, generador de respaldo y estacionamiento para 3 vehículos.",
  },
  {
    id: "31",
    title: "Residencia colonial restaurada — Centro de las Obras",
    slug: "casa-centro-obras",
    price: 295000,
    currency: "USD",
    type: "venta",
    category: "Casa",
    city: "Santo Domingo",
    zone: "Centro de las Obras",
    beds: 3,
    baths: 2,
    areaM2: 185,
    verified: true,
    featured: false,
    image: getUnsplash("colonial"),
    images: [
      getUnsplash("colonial"),
      getUnsplash("interior_1"),
      getUnsplash("interior_3"),
      getUnsplash("property_9"),
      getUnsplash("property_10"),
    ],
    lat: 18.4715,
    lng: -69.8892,
    amenities: ["terrace", "balcony", "garden", "security", "storage"],
    description:
      "Casa colonial del siglo XIX completamente restaurada con acabados de lujo contemporáneos. 185 m² con vigas originales de madera de cedro, techos de doble altura y patios interiores con fuentes de azulejos artesanales. 3 habitaciones con closets empotrados, 2 baños con porcelanato importado y cocina moderna con isla. Balcón con vista a la catedral.",
  },
  {
    id: "32",
    title: "Villa con jardín de rosas — Wajacay Abajo",
    slug: "villa-wajacay",
    price: 165000,
    currency: "USD",
    type: "venta",
    category: "Casa",
    city: "Santo Domingo",
    zone: "Wajacay Abajo",
    beds: 3,
    baths: 2,
    areaM2: 160,
    verified: false,
    featured: false,
    image: getUnsplash("garden_view_1"),
    images: [
      getUnsplash("garden_view_1"),
      getUnsplash("garden_view_2"),
      getUnsplash("garden_view_3"),
      getUnsplash("property_5"),
      getUnsplash("property_6"),
    ],
    lat: 18.4556,
    lng: -69.9501,
    amenities: ["garden", "parking", "security", "terrace", "pet-friendly"],
    description:
      "Casa unifamiliar rodeada de un jardín de rosas con más de 200 variedades. 160 m² de distribución acogedora con sala con chimenea, comedor para 8 personas y cocina con despensa. 3 habitaciones con closets, 2 baños completos y patio trasero con parrillera. Estacionamiento techado para 2 vehículos. Zona residencial tranquila con acceso a escuelas y centros comerciales.",
  },

  // === TERRENOS Y PROYECTOS DE INVERSIÓN ===

  {
    id: "6",
    title: "Terreno comercial Av. Winston Churchill",
    slug: "terreno-churchill",
    price: 450000,
    currency: "USD",
    type: "venta",
    category: "Terreno",
    city: "Santo Domingo",
    zone: "Ensanche Julieta",
    beds: 0,
    baths: 0,
    areaM2: 800,
    verified: true,
    featured: false,
    image: getUnsplash("land_1"),
    images: [
      getUnsplash("land_1"),
      getUnsplash("land_2"),
      getUnsplash("land_3"),
      getUnsplash("land_4"),
      getUnsplash("land_5"),
    ],
    lat: 18.4689,
    lng: -69.9421,
    amenities: ["corner", "high-traffic", "fence"],
    description:
      "Esquina de alto tráfico en la avenida más prestigiosa de Santo Domingo, con más de 50,000 vehículos diarios. 800 m² planos con frente de 25 m y profundidad de 32 m. Documentación al día, libre de gravámenes. Ideal para desarrollo mixto de retail, oficinas o torre residencial. Estudios de suelo disponibles con capacidad de construir hasta 8 pisos según ordenanza municipal.",
  },
  {
    id: "14",
    title: "Terreno residencial en Veron",
    slug: "terreno-veron",
    price: 95000,
    currency: "USD",
    type: "venta",
    category: "Terreno",
    city: "Punta Cana",
    zone: "Veron",
    beds: 0,
    baths: 0,
    areaM2: 500,
    verified: true,
    featured: false,
    image: getUnsplash("land_3"),
    images: [
      getUnsplash("land_3"),
      getUnsplash("land_1"),
      getUnsplash("land_4"),
      getUnsplash("land_5"),
      getUnsplash("land_2"),
    ],
    lat: 18.6144,
    lng: -68.4112,
    amenities: ["fence", "high-traffic"],
    description:
      "Lote plano de 500 m² con servicios públicos en vía de asfalto recién extendida. Permite construcción residencial de hasta 2 pisos más terraza. Zona de rápido crecimiento con nuevas urbanizaciones y centros comerciales. Documentación al día, título de propiedad registrado en la DGII y SDUI. Ideal para vivienda familiar o proyecto de inversión inmobiliaria.",
  },
  {
    id: "25",
    title: "Solares en proyecto Bávaro — inversión",
    slug: "lotes-bavaro",
    price: 78000,
    currency: "USD",
    type: "venta",
    category: "Terreno",
    city: "Punta Cana",
    zone: "Bávaro",
    beds: 0,
    baths: 0,
    areaM2: 300,
    verified: true,
    featured: false,
    image: getUnsplash("land_5"),
    images: [
      getUnsplash("land_5"),
      getUnsplash("land_3"),
      getUnsplash("land_1"),
      getUnsplash("land_4"),
      getUnsplash("land_2"),
    ],
    lat: 18.5367,
    lng: -68.4049,
    amenities: ["fence", "beach-access"],
    description:
      "Paquete de dos solares contiguos de 300 m² cada uno, planos y con estudios de suelo disponibles. Ubicados a 5 minutos caminando de la playa de Bávaro. Proyecto de desarrollo turístico con uso mixto permitido (hotel boutique, restaurante o residencia de lujo). El vendedor ofrece acompañamiento legal y técnico para el proceso de construcción.",
  },
  {
    id: "33",
    title: "Terreno montañoso con vista — Jarabacoa",
    slug: "terreno-jarabacoa-montana",
    price: 120000,
    currency: "USD",
    type: "venta",
    category: "Terreno",
    city: "Jarabacoa",
    zone: "Rincón de la Vieja",
    beds: 0,
    baths: 0,
    areaM2: 2000,
    verified: true,
    featured: false,
    image: getUnsplash("mountain_1"),
    images: [
      getUnsplash("mountain_1"),
      getUnsplash("mountain_2"),
      getUnsplash("mountain_3"),
      getUnsplash("land_4"),
      getUnsplash("land_5"),
    ],
    lat: 19.1250,
    lng: -70.6350,
    amenities: ["garden", "fence"],
    description:
      "Parcela de 2,000 m² con vista panorámica al valle del Yaque de Jarabacoa y las montañas de la Cordillera Central. Terreno semiplano con acceso por camino pavimentado y servicios eléctricos a 100 metros. Ideal para proyecto eco-turístico, cabañas o residencia de fin de semana. Arroyo natural cercano y vegetación nativa de pino y palmeja.",
  },

  // === OFICINAS Y ESPACIOS COMERCIALES ===

  {
    id: "10",
    title: "Oficina Class A — Torre en Piantini",
    slug: "oficina-piantini",
    price: 4500,
    currency: "USD",
    type: "alquiler",
    category: "Oficina",
    city: "Santo Domingo",
    zone: "Piantini",
    beds: 0,
    baths: 2,
    areaM2: 210,
    verified: true,
    featured: false,
    image: getUnsplash("office_1"),
    images: [
      getUnsplash("office_1"),
      getUnsplash("office_2"),
      getUnsplash("office_3"),
      getUnsplash("office_4"),
      getUnsplash("office_5"),
    ],
    lat: 18.4751,
    lng: -69.9268,
    amenities: ["elevator", "security", "parking", "coworking", "wifi", "concierge"],
    description:
      "Módulo corporativo de 210 m² en torre Class A del centro financiero de Piantini. Incluye recepción con recepcionista, 4 estaciones de trabajo privativas, sala de juntas para 12 personas, cocina equipada y 2 baños completos. Acceso controlado 24/7, estacionamiento subterráneo para 4 vehículos, gimnasio en el edificio y servicio de concierge. Contrato mínimo anual.",
  },
  {
    id: "21",
    title: "Suite corporativa amueblada — Naco",
    slug: "oficina-coworking-naco",
    price: 2800,
    currency: "USD",
    type: "alquiler",
    category: "Oficina",
    city: "Santo Domingo",
    zone: "Naco",
    beds: 0,
    baths: 1,
    areaM2: 68,
    verified: true,
    featured: false,
    image: getUnsplash("office_3"),
    images: [
      getUnsplash("office_3"),
      getUnsplash("office_1"),
      getUnsplash("office_2"),
      getUnsplash("office_4"),
      getUnsplash("office_5"),
    ],
    lat: 18.4682,
    lng: -69.9344,
    amenities: ["wifi", "furnished", "coworking", "concierge", "ac", "elevator"],
    description:
      "Módulo plug & play de 68 m² con mobiliario de diseño, salas de juntas compartidas y café ilimitado. Incluye internet de fibra óptica dedicada, limpieza diaria, servicio de correo y atención telefónica. Ideal para freelancers, consultores o equipos pequeños de hasta 4 personas. Contrato flexible mensual con opción a privado.",
  },
  {
    id: "24",
    title: "Local gastronómico — Calle El Conde",
    slug: "local-el-conde",
    price: 6500,
    currency: "USD",
    type: "alquiler",
    category: "Local comercial",
    city: "Santo Domingo",
    zone: "Ciudad Colonial",
    beds: 0,
    baths: 2,
    areaM2: 95,
    verified: true,
    featured: false,
    image: getUnsplash("hotel_2"),
    images: [
      getUnsplash("hotel_2"),
      getUnsplash("garden_2"),
      getUnsplash("street_1"),
      getUnsplash("garden_2"),
      getUnsplash("colonial"),
    ],
    lat: 18.4736,
    lng: -69.8844,
    amenities: ["high-traffic", "terrace", "commercial-ready", "storage"],
    description:
      "Local comercial de 95 m² en la calle peatonal más transitada del Caribe, con más de 15,000 personas diarias. Listo para gastrobar o retail especializado: incluye extracción de humos, instalación de gas, baño adaptado y terraza de 15 m² habilitada. Arrendamiento con depósito de 2 meses y pago anticipado anual.",
  },
  {
    id: "9",
    title: "Local comercial esquina — Los Jardines",
    slug: "local-jardines-santiago",
    price: 185000,
    currency: "USD",
    type: "venta",
    category: "Local comercial",
    city: "Santiago",
    zone: "Los Jardines",
    beds: 0,
    baths: 2,
    areaM2: 165,
    verified: true,
    featured: false,
    image: getUnsplash("commercial_1"),
    images: [
      getUnsplash("commercial_1"),
      getUnsplash("commercial_2"),
      getUnsplash("commercial_3"),
      getUnsplash("commercial_4"),
      getUnsplash("interior_5"),
    ],
    lat: 19.4512,
    lng: -70.7045,
    amenities: ["corner", "high-traffic", "parking", "storage", "commercial-ready"],
    description:
      "Planta libre de 165 m² con doble altura (5.5 m), ideal para retail, farmacia o showroom. Esquina de alto tráfico en la zona comercial de mayor crecimiento de Santiago. Incluye baño para discapacitados, sistema de rociadores y conexión trifásica. Estacionamiento para 5 vehículos en la fachada. Documentación lista para licencia comercial inmediata.",
  },

  // === INDUSTRIAL Y ALMACÉN ===

  {
    id: "17",
    title: "Nave industrial con andén — Haina",
    slug: "nave-haina",
    price: 420000,
    currency: "USD",
    type: "venta",
    category: "Nave industrial",
    city: "San Cristóbal",
    zone: "Haina",
    beds: 0,
    baths: 2,
    areaM2: 1850,
    verified: true,
    featured: false,
    image: getUnsplash("commercial_4"),
    images: [
      getUnsplash("commercial_4"),
      getUnsplash("commercial_3"),
      getUnsplash("commercial_2"),
      getUnsplash("commercial_1"),
      getUnsplash("interior_5"),
    ],
    lat: 18.4191,
    lng: -70.0364,
    amenities: ["storage", "fence", "high-traffic", "parking", "commercial-ready"],
    description:
      "Nave industrial de 1,850 m² con techos de 8 metros, muelle de carga a nivel de piso y puerta seccional de 4x4 m. Subestación eléctrica dedicada de 200 kVA, piso de hormigón reforzado para tráfico pesado y perímetro cercado con garita de seguridad. Ubicada en la zona industrial de Haina, a 15 minutos del puerto y del aeropuerto internacional.",
  },

  // === HOTEL Y HOSPEDAJE ===

  {
    id: "18",
    title: "Hotel boutique 12 habitaciones — Las Terrenas",
    slug: "hotel-las-terrenas",
    price: 2400000,
    currency: "USD",
    type: "venta",
    category: "Hotel / hospedaje",
    city: "Samaná",
    zone: "Las Terrenas",
    beds: 12,
    baths: 14,
    areaM2: 640,
    verified: true,
    featured: true,
    promo: true,
    image: getUnsplash("hotel_1"),
    images: [
      getUnsplash("hotel_1"),
      getUnsplash("hotel_2"),
      getUnsplash("office_5"),
      getUnsplash("office_2"),
      getUnsplash("office_3"),
    ],
    lat: 19.321,
    lng: -69.5389,
    amenities: ["pool", "restaurant", "spa", "parking", "wifi", "beach-access"],
    description:
      "Operación turística establecida con 12 habitaciones, restaurante con licencia sanitaria, spa al aire libre y piscina rodeada de jardines tropicales. Ingresos brutos anuales de $320,000 con ocupación promedio del 68%. Todas las habitaciones con vista al mar, aire acondicionado, Smart TV y minibar. Personal completo incluido: gerente, recepción, cocina, limpieza y mantenimiento. Licencia turística vigente hasta 2030.",
  },

  // === EDIFICIOS DE INVERSIÓN ===

  {
    id: "15",
    title: "Edificio de apartamentos — renta consolidada",
    slug: "edificio-san-pedro",
    price: 1850000,
    currency: "USD",
    type: "venta",
    category: "Edificio",
    city: "San Pedro de Macorís",
    zone: "Centro",
    beds: 0,
    baths: 0,
    areaM2: 980,
    verified: true,
    featured: false,
    image: getUnsplash("interior_5"),
    images: [
      getUnsplash("interior_5"),
      getUnsplash("commercial_3"),
      getUnsplash("commercial_4"),
      getUnsplash("commercial_1"),
      getUnsplash("commercial_2"),
    ],
    lat: 18.4574,
    lng: -69.3064,
    amenities: ["parking", "security", "elevator", "storage", "commercial-ready"],
    description:
      "Activo mixto de 3 plantas con 12 unidades en operación y estacionamiento techado para 8 vehículos. Ingreso anual por rentas de $145,000 con tasa de ocupación del 92%. Planta baja con local comercial (anchor tenant: farmacia cadena), pisos superiores con apartamentos de 2 y 3 habitaciones. Sistema eléctrico e hidráulico independiente por unidad. Valor de avalúo superior al precio de venta.",
  },

  // === ESTUDIOS Y DEPARTAMENTOS ECONÓMICOS ===

  {
    id: "7",
    title: "Estudio amueblado cerca de UASD — Gazcue",
    slug: "estudio-gazcue",
    price: 28500,
    currency: "DOP",
    type: "alquiler",
    category: "Estudio",
    city: "Santo Domingo",
    zone: "Gazcue",
    beds: 0,
    baths: 1,
    areaM2: 38,
    verified: true,
    featured: false,
    image: getUnsplash("interior_1"),
    images: [
      getUnsplash("interior_1"),
      getUnsplash("interior_2"),
      getUnsplash("interior_3"),
      getUnsplash("interior_4"),
      getUnsplash("interior_5"),
    ],
    lat: 18.4712,
    lng: -69.9011,
    amenities: ["furnished", "wifi", "ac", "elevator", "security"],
    description:
      "Estudio listo para habitar: cama queen, cocina integral con microondas, refrigerador americano y internet de alta velocidad. Ubicado a 5 minutos caminando de la UASD y del Parque Francisco Javier Dogo. Edificio con ascensor, vigilancia 24/7 y lavandería comunitaria. Ideal estudiantes o jóvenes profesionales.",
  },
  {
    id: "16",
    title: "Estudio económico — Andrés, Boca Chica",
    slug: "estudio-boca-chica",
    price: 12000,
    currency: "DOP",
    type: "alquiler",
    category: "Estudio",
    city: "Boca Chica",
    zone: "Andrés",
    beds: 0,
    baths: 1,
    areaM2: 32,
    verified: false,
    featured: false,
    image: getUnsplash("interior_2"),
    images: [
      getUnsplash("interior_2"),
      getUnsplash("interior_4"),
      getUnsplash("interior_3"),
      getUnsplash("interior_1"),
      getUnsplash("interior_5"),
    ],
    lat: 18.4449,
    lng: -69.6102,
    amenities: ["wifi", "ac", "furnished"],
    description:
      "Opción accesible cerca de playa pública, ideal estudiantes o nómadas. 32 m² amueblados con cocina compartida en el patio. A 10 minutos de la zona hotelera de Boca Chica. Transporte público a 50 metros. Agua y luz incluidas en el arrendamiento mensual.",
  },

  // === FINCAS Y TERRENOS RURALES ===

  {
    id: "11",
    title: "Finca con río y casa de madera — Jarabacoa",
    slug: "finca-jarabacoa",
    price: 320000,
    currency: "USD",
    type: "venta",
    category: "Finca",
    city: "Jarabacoa",
    zone: "Buena Vista",
    beds: 4,
    baths: 3,
    areaM2: 320,
    verified: true,
    featured: true,
    image: getUnsplash("farm_1"),
    images: [
      getUnsplash("farm_1"),
      getUnsplash("land_4"),
      getUnsplash("land_5"),
      getUnsplash("land_2"),
      getUnsplash("land_3"),
    ],
    lat: 19.1189,
    lng: -70.6481,
    amenities: ["garden", "parking", "solar", "storage", "pet-friendly"],
    description:
      "Altitud fresca de 600 msnm, parcela mixta agrícola-recreativa de 5 hectáreas con casa principal de 320 m² en madera de pino nativo. Río natural con piscina formada para nadar, senderos ecológicos y huerto orgánico de frutas tropicales. La casa cuenta con 4 habitaciones, 3 baños, chimenea y sistema solar de 5 kW. Ideal para turismo de naturaleza o residencia principal.",
  },

  // ========================================
  // === NUEVAS PROPIEDADES (ADICIONALES) ===
  // ========================================

  {
    id: "34",
    title: "Penthouse de lujo con piscina privada — Naco",
    slug: "penthouse-lujo-naco",
    price: 520000,
    currency: "USD",
    type: "venta",
    category: "Penthouse",
    city: "Santo Domingo",
    zone: "Naco",
    beds: 4,
    baths: 4,
    areaM2: 310,
    verified: true,
    featured: true,
    promo: true,
    image: getUnsplash("condo_1"),
    images: [
      getUnsplash("condo_1"),
      getUnsplash("condo_2"),
      getUnsplash("luxury_int_3"),
      getUnsplash("luxury_int_4"),
      getUnsplash("property_1"),
    ],
    lat: 18.4670,
    lng: -69.9280,
    amenities: ["pool", "gym", "terrace", "security", "elevator", "concierge", "ocean-view"],
    description:
      "Penthouse de lujo absoluto con piscina privada desbordante de 15 m² en la azotea. 310 m² de diseño contemporáneo con doble altura en sala, cocina italiana Boffi y baños de mármol Calacatta. 4 suites con walk-in closet y sistema de sonido integrado. Terraza de 60 m² con jacuzzi, cocina de verano y vista 360° al valle y al mar.",
  },
  {
    id: "35",
    title: "Apartamento de playa — Bayahibe",
    slug: "apto-bayahibe",
    price: 175000,
    currency: "USD",
    type: "venta",
    category: "Apartamento",
    city: "Bayahibe",
    zone: "Bahía de las Águilas",
    beds: 2,
    baths: 2,
    areaM2: 88,
    verified: true,
    featured: false,
    image: getUnsplash("beach_house"),
    images: [
      getUnsplash("beach_house"),
      getUnsplash("tropical_1"),
      getUnsplash("tropical_2"),
      getUnsplash("property_6"),
      getUnsplash("property_7"),
    ],
    lat: 18.1500,
    lng: -68.7800,
    amenities: ["pool", "parking", "security", "ocean-view", "beach-access", "wifi"],
    description:
      "Apartamento de primer línea en el exclusivo balneario de Bayahibe. 88 m² con vistas panorámicas al mar Caribe desde cada habitación. Piso de madera tropical, cocina equipada con electrodomésticos de alta gama y balcón perimetral. Acceso directo a playa virgen, piscina compartida, restaurante en el complejo y servicio de ferry a Isla Saona.",
  },
  {
    id: "36",
    title: "Casa con vista al valle — Loma de Manuel",
    slug: "casa-loma-manuel",
    price: 210000,
    currency: "USD",
    type: "venta",
    category: "Casa",
    city: "Santo Domingo",
    zone: "Loma de Manuel",
    beds: 3,
    baths: 2,
    areaM2: 175,
    verified: false,
    featured: false,
    image: getUnsplash("garden_view_2"),
    images: [
      getUnsplash("garden_view_2"),
      getUnsplash("modern_ext_3"),
      getUnsplash("interior_1"),
      getUnsplash("property_8"),
      getUnsplash("property_9"),
    ],
    lat: 18.4400,
    lng: -69.9650,
    amenities: ["garden", "parking", "terrace", "security", "pet-friendly"],
    description:
      "Casa de dos niveles con vista panorámica al valle y la ciudad. 175 m² en urbanización tranquila de acceso controlado. Sala con chimenea, comedor para 10, cocina con isla y despensa. 3 habitaciones con closets, 2 baños completos y terraza con parrillera. Jardín frontlateral con árboles frutales. Estacionamiento techado para 2 vehículos.",
  },
  {
    id: "37",
    title: "Loft creativo — Malecón 21 de Septiembre",
    slug: "loft-malecon",
    price: 4500,
    currency: "USD",
    type: "alquiler",
    category: "Loft",
    city: "Santo Domingo",
    zone: "Malecón",
    beds: 1,
    baths: 1,
    areaM2: 75,
    verified: true,
    featured: false,
    image: getUnsplash("condo_3"),
    images: [
      getUnsplash("condo_3"),
      getUnsplash("loft"),
      getUnsplash("interior_4"),
      getUnsplash("property_10"),
      getUnsplash("property_5"),
    ],
    lat: 18.4620,
    lng: -69.9000,
    amenities: ["wifi", "ac", "furnished", "security", "elevator", "balcony"],
    description:
      "Loft de diseño con vista al Mar Caribe y el Malecón 21 de Septiembre. 75 m² con distribución abierta, cocina modular de acero inoxidable y baño con acabados de diseñador. Amueblado con piezas de autor y equipado con sistema de sonido Bose. Edificio con seguridad 24/7, gimnasio y terraza en la azotea. Ideal para profesionales creativos.",
  },
  {
    id: "38",
    title: "Villa con viñedo — Valle del Cibao",
    slug: "villa-vinedo-cibao",
    price: 450000,
    currency: "USD",
    type: "venta",
    category: "Villa",
    city: "San Francisco de Macorís",
    zone: "Valle Nuevo",
    beds: 5,
    baths: 4,
    areaM2: 350,
    verified: true,
    featured: false,
    image: getUnsplash("tropical_3"),
    images: [
      getUnsplash("tropical_3"),
      getUnsplash("farm_2"),
      getUnsplash("mountain_2"),
      getUnsplash("property_4"),
      getUnsplash("luxury_villa"),
    ],
    lat: 19.2150,
    lng: -70.0100,
    amenities: ["pool", "garden", "parking", "security", "terrace", "solar"],
    description:
      "Villa con viñedo productivo de 2 hectáreas y bodega de producción de vino. 350 m² de residencia principal con arquitectura rústica moderna, vigas de roble y pisos de terrazo artesanal. 5 habitaciones, 4 baños, bodega climatificada para 500 botellas y sala de degustación con vista al valle. Piscina natural rodeada de vegetación tropical.",
  },
  {
    id: "39",
    title: "Departamento ejecutivo — Zona Industrial de Santiago",
    slug: "depto-zona-industrial-santiago",
    price: 150000,
    currency: "USD",
    type: "venta",
    category: "Apartamento",
    city: "Santiago",
    zone: "Zona Industrial",
    beds: 2,
    baths: 1,
    areaM2: 72,
    verified: true,
    featured: false,
    image: getUnsplash("condo_4"),
    images: [
      getUnsplash("condo_4"),
      getUnsplash("condo_5"),
      getUnsplash("interior_2"),
      getUnsplash("property_6"),
      getUnsplash("property_8"),
    ],
    lat: 19.4400,
    lng: -70.6900,
    amenities: ["parking", "elevator", "security", "gym", "ac"],
    description:
      "Departamento moderno en torre de 12 pisos cerca de la zona industrial. 72 m² con distribución eficiente: sala-comedor, cocina equipada, 2 habitaciones y baño completo. A 5 minutos del centro de distribución logística más grande del norte. Ideal para ejecutivos industriales. Estacionamiento incluido y gimnasio en el edificio.",
  },
  {
    id: "40",
    title: "Finca ganadera — El Seibo",
    slug: "finca-ganadera-el-seibo",
    price: 580000,
    currency: "USD",
    type: "venta",
    category: "Finca",
    city: "El Seibo",
    zone: "Sabana Grande",
    beds: 3,
    baths: 2,
    areaM2: 450,
    verified: true,
    featured: false,
    image: getUnsplash("land_4"),
    images: [
      getUnsplash("land_4"),
      getUnsplash("land_5"),
      getUnsplash("farm_1"),
      getUnsplash("mountain_3"),
      getUnsplash("garden_1"),
    ],
    lat: 18.6200,
    lng: -68.7100,
    amenities: ["garden", "parking", "storage", "pet-friendly"],
    description:
      "Finca ganadera de 50 hectáreas con casa principal de 450 m², establos modernos, corrales y sistema de riego por goteo. Capacidad para 200 cabezas de ganado con pasturas mejoradas de estrella-graama. La casa tiene 3 habitaciones, 2 baños, sala amplia, cocina industrial y bodega. Poza de agua natural y camino de acceso pavimentado hasta la propiedad.",
  },
  {
    id: "41",
    title: "Penthouse corporativo — Torre Executive, Piantini",
    slug: "pentho-executive-piantini",
    price: 680000,
    currency: "USD",
    type: "venta",
    category: "Penthouse",
    city: "Santo Domingo",
    zone: "Piantini",
    beds: 3,
    baths: 3,
    areaM2: 275,
    verified: true,
    featured: true,
    promo: true,
    image: getUnsplash("condo_2"),
    images: [
      getUnsplash("condo_2"),
      getUnsplash("condo_1"),
      getUnsplash("luxury_int_5"),
      getUnsplash("luxury_int_1"),
      getUnsplash("property_3"),
    ],
    lat: 18.4760,
    lng: -69.9250,
    amenities: ["pool", "gym", "terrace", "security", "elevator", "concierge", "ocean-view", "parking"],
    description:
      "Penthouse corporativo en la torre más emblemática de Piantini. 275 m² con acabados de lujo, domótica Savant y sistema de filtración de aire HEPA. 3 suites con closets diseñados por Closetspace, cocina Bulthaup con isla en obsidiana. Terraza de 50 m² con piscina desbordante y vista al centro financiero y el mar.",
  },
  {
    id: "42",
    title: "Casa de huéspedes — Las Galeras",
    slug: "casa-huespedes-galeras",
    price: 340000,
    currency: "USD",
    type: "venta",
    category: "Casa",
    city: "Samaná",
    zone: "Las Galeras",
    beds: 5,
    baths: 4,
    areaM2: 290,
    verified: false,
    featured: false,
    image: getUnsplash("tropical_1"),
    images: [
      getUnsplash("tropical_1"),
      getUnsplash("beach_house"),
      getUnsplash("garden_view_3"),
      getUnsplash("property_2"),
      getUnsplash("property_5"),
    ],
    lat: 19.4800,
    lng: -69.2000,
    amenities: ["pool", "garden", "parking", "security", "ocean-view", "beach-access"],
    description:
      "Casa de huéspedes con 5 habitaciones independientes y piscina rodeada de palmeras. 290 m² ubicados a 3 minutos caminando de la playa de Las Galeras. Ideal para Airbnb o negocio de hospedaje: ya cuenta con licencia turística, mobiliario completo y personal en operación. Ingreso mensual promedio de $3,500 con ocupación del 75%.",
  },
  {
    id: "43",
    title: "Oficina compartida — Edificio Financiero, Naco",
    slug: "oficina-compartida-naco",
    price: 800,
    currency: "USD",
    type: "alquiler",
    category: "Oficina",
    city: "Santo Domingo",
    zone: "Naco",
    beds: 0,
    baths: 1,
    areaM2: 15,
    verified: true,
    featured: false,
    image: getUnsplash("office_4"),
    images: [
      getUnsplash("office_4"),
      getUnsplash("office_5"),
      getUnsplash("office_1"),
      getUnsplash("office_2"),
      getUnsplash("office_3"),
    ],
    lat: 18.4690,
    lng: -69.9330,
    amenities: ["wifi", "furnished", "coworking", "ac", "elevator"],
    description:
      "Escritorio privado en oficina compartida del centro financiero de Naco. 15 m² con escritorio ergonómico, archivador y acceso a sala de reuniones compartida. Incluye internet de fibra óptica, limpieza diaria, servicio de café y atención de correspondencia. Contrato mensual flexible. A pasos de centros comerciales y restaurantes.",
  },
  {
    id: "44",
    title: "Local en centro comercial — Plaza Central, Santo Domingo",
    slug: "local-plaza-central",
    price: 8500,
    currency: "USD",
    type: "alquiler",
    category: "Local comercial",
    city: "Santo Domingo",
    zone: "Centro Histórico",
    beds: 0,
    baths: 1,
    areaM2: 55,
    verified: true,
    featured: false,
    image: getUnsplash("commercial_2"),
    images: [
      getUnsplash("commercial_2"),
      getUnsplash("commercial_3"),
      getUnsplash("interior_5"),
      getUnsplash("property_7"),
      getUnsplash("property_9"),
    ],
    lat: 18.4700,
    lng: -69.8900,
    amenities: ["high-traffic", "security", "commercial-ready"],
    description:
      "Local de 55 m² en el centro comercial más transitado del Caribe con más de 2 millones de visitantes mensuales. Planta baja con vitrina de 6 m de frente, iluminación LED y aire acondicionado central. Ideal para retail de moda, tecnología o accesorios. Contrato con opción a renovación. El centro comercial se encarga de la gestión de marketing y eventos.",
  },
  {
    id: "45",
    title: "Almacén logístico — Zona Franca, Santo Domingo",
    slug: "almacen-zona-franca",
    price: 1200000,
    currency: "USD",
    type: "venta",
    category: "Nave industrial",
    city: "Santo Domingo",
    zone: "Zona Franca",
    beds: 0,
    baths: 3,
    areaM2: 3500,
    verified: true,
    featured: false,
    image: getUnsplash("warehouse_1"),
    images: [
      getUnsplash("warehouse_1"),
      getUnsplash("warehouse_2"),
      getUnsplash("commercial_4"),
      getUnsplash("commercial_1"),
      getUnsplash("commercial_2"),
    ],
    lat: 18.4500,
    lng: -69.9600,
    amenities: ["storage", "fence", "high-traffic", "parking", "commercial-ready"],
    description:
      "Almacén logístico de 3,500 m² en la Zona Franca más grande del Caribe. 4 muelles de carga, sistema de sprinklers, iluminación LED industrial y perímetro con control de acceso biométrico. Capacidad para 2,000 palés con racking móvil. Conexión directa a autopista y a 10 minutos del puerto. Contrato de arrendamiento corporativo existente por 5 años.",
  },
  {
    id: "46",
    title: "Residencia sostenible con huerto urbano — Higüey",
    slug: "residencia-huerto-higuey",
    price: 195000,
    currency: "USD",
    type: "venta",
    category: "Casa",
    city: "Higüey",
    zone: "Urb. Solcar",
    beds: 3,
    baths: 2,
    areaM2: 150,
    verified: true,
    featured: false,
    image: getUnsplash("garden_view_3"),
    images: [
      getUnsplash("garden_view_3"),
      getUnsplash("garden_1"),
      getUnsplash("property_10"),
      getUnsplash("interior_3"),
      getUnsplash("modern_ext_4"),
    ],
    lat: 18.4450,
    lng: -68.2500,
    amenities: ["garden", "parking", "solar", "pet-friendly", "storage"],
    description:
      "Casa sustentable con huerto urbano orgánico y sistema de compostaje. 150 m² construidos con materiales locales: bloque de coco, madera reciclada y piso de cemento pulido. Techos verdes con aislamiento térmico natural, cisterna de 10,000 litros y paneles solares para agua caliente. 3 habitaciones con ventilación cruzada y 2 baños con tratamiento natural de aguas.",
  },

  // === PROPIEDADES ADICIONALES (47-70) ===

  {
    id: "47",
    title: "Penthouse de lujo con terraza panorámica — Torre Alcobendas",
    slug: "penthouse-alcobendas",
    price: 750000,
    currency: "USD",
    type: "venta",
    category: "Penthouse",
    city: "Santo Domingo",
    zone: "Alcobendas",
    beds: 4,
    baths: 4,
    areaM2: 330,
    verified: true,
    featured: true,
    promo: true,
    image: getUnsplash("condo_1"),
    images: [
      getUnsplash("condo_1"),
      getUnsplash("condo_2"),
      getUnsplash("luxury_int_1"),
      getUnsplash("luxury_int_3"),
      getUnsplash("property_1"),
    ],
    lat: 18.4780,
    lng: -69.9200,
    amenities: ["pool", "gym", "terrace", "security", "elevator", "concierge", "ocean-view", "parking"],
    description:
      "Penthouse de diseño exclusivo en la torre más prestigiosa de Alcobendas. 330 m² con doble altura en sala social, terraza panorámica de 80 m² con piscina desbordante y jacuzzi. 4 suites con closets de diseñador, cocina Boffi con isla en silestone, domótica Crestron y sistema de sonido integrado. Vista 360° al mar Caribe y Cordillera Central.",
  },
  {
    id: "48",
    title: "Casa minimalista con piscina infinity — Bávaro",
    slug: "casa-minimalista-bavaro",
    price: 620000,
    currency: "USD",
    type: "venta",
    category: "Casa",
    city: "Punta Cana",
    zone: "Bávaro",
    beds: 4,
    baths: 4,
    areaM2: 340,
    verified: true,
    featured: false,
    image: getUnsplash("modern_ext_1"),
    images: [
      getUnsplash("modern_ext_1"),
      getUnsplash("modern_ext_2"),
      getUnsplash("modern_ext_3"),
      getUnsplash("luxury_int_2"),
      getUnsplash("property_4"),
    ],
    lat: 18.5400,
    lng: -68.4100,
    amenities: ["pool", "garden", "parking", "security", "ocean-view", "solar", "ac"],
    description:
      "Residencia minimalista de autor con piscina infinity que se funde visualmente con el horizonte. 340 m² de arquitectura contemporánea con muros cortavidrio, pisos de porcelanato rectificado de 80 cm y techos de 3.5 metros. 4 suites con acceso al jardín, cocina Gaggenau completa, sistema de energía solar con baterías y estacionamiento para 3 vehículos.",
  },
  {
    id: "49",
    title: "Apartamento premium — World Trade Center, Santo Domingo",
    slug: "apto-wtc-santo-domingo",
    price: 5500,
    currency: "USD",
    type: "alquiler",
    category: "Apartamento",
    city: "Santo Domingo",
    zone: "Zona Colonial",
    beds: 2,
    baths: 2,
    areaM2: 120,
    verified: true,
    featured: false,
    image: getUnsplash("condo_3"),
    images: [
      getUnsplash("condo_3"),
      getUnsplash("condo_4"),
      getUnsplash("interior_1"),
      getUnsplash("interior_2"),
      getUnsplash("property_6"),
    ],
    lat: 18.4790,
    lng: -69.9100,
    amenities: ["parking", "elevator", "security", "gym", "wifi", "ac", "furnished"],
    description:
      "Apartamento completamente amueblado en el edificio más icónico de Santo Domingo. 120 m² con vista panorámica al malecón y el río Ozama. Cocina premium con electrodomésticos Miele, pisos de madera de roble americano y aire acondicionado Daikin inverter. El edificio cuenta con gimnasio de clase mundial, piscina olímpica, spa, salón de eventos y seguridad 24/7.",
  },
  {
    id: "50",
    title: "Villa rústica con cascada privada — Jarabacoa",
    slug: "villa-cascada-jarabacoa",
    price: 380000,
    currency: "USD",
    type: "venta",
    category: "Villa",
    city: "Jarabacoa",
    zone: "Rincón de la Vieja",
    beds: 4,
    baths: 3,
    areaM2: 280,
    verified: true,
    featured: false,
    image: getUnsplash("mountain_1"),
    images: [
      getUnsplash("mountain_1"),
      getUnsplash("mountain_2"),
      getUnsplash("farm_2"),
      getUnsplash("property_3"),
      getUnsplash("luxury_villa"),
    ],
    lat: 19.1300,
    lng: -70.6400,
    amenities: ["pool", "garden", "parking", "security", "terrace", "solar"],
    description:
      "Villa rústica-chic rodeada de naturaleza exuberante con cascada natural privada a 50 metros. 280 m² construidos en piedra natural, madera de roble y vidrio. 4 habitaciones con chimenea, 3 baños con grifería Brizo, cocina de chef con isla en granito. Piscina natural formada por el arroyo, terraza con hamacas y fogata.",
  },
  {
    id: "51",
    title: "Duplex moderno — Ensanche León",
    slug: "duplex-leon",
    price: 185000,
    currency: "USD",
    type: "venta",
    category: "Casa",
    city: "Santo Domingo",
    zone: "Ensanche León",
    beds: 3,
    baths: 2,
    areaM2: 165,
    verified: true,
    featured: false,
    image: getUnsplash("modern_ext_4"),
    images: [
      getUnsplash("modern_ext_4"),
      getUnsplash("modern_ext_5"),
      getUnsplash("interior_3"),
      getUnsplash("property_7"),
      getUnsplash("property_8"),
    ],
    lat: 18.4580,
    lng: -69.9400,
    amenities: ["parking", "garden", "security", "terrace", "ac"],
    description:
      "Duplex de diseño contemporáneo con fachada arquitectónica premiada. 165 m² distribuidos en 3 niveles: planta baja con sala de visitas, primer nivel con sala-comedor-kitchenette, segundo nivel con 3 habitaciones y terraza solarium. Acabados en concreto pulido, madera natural y metal negro. Estacionamiento en calle para 2 vehículos.",
  },
  {
    id: "52",
    title: "Oficina ejecutiva amueblada — Piantini",
    slug: "oficina-ejecutiva-piantini",
    price: 3500,
    currency: "USD",
    type: "alquiler",
    category: "Oficina",
    city: "Santo Domingo",
    zone: "Piantini",
    beds: 0,
    baths: 2,
    areaM2: 150,
    verified: true,
    featured: false,
    image: getUnsplash("office_2"),
    images: [
      getUnsplash("office_2"),
      getUnsplash("office_3"),
      getUnsplash("office_4"),
      getUnsplash("office_5"),
      getUnsplash("interior_5"),
    ],
    lat: 18.4740,
    lng: -69.9280,
    amenities: ["elevator", "security", "parking", "coworking", "wifi", "ac"],
    description:
      "Oficina ejecutiva de 150 m² completamente amueblada con mobiliario de diseño italiano. Incluye 4 estaciones de trabajo privativas, sala de reuniones para 10 personas, archivador y cocina auxiliar. Internet de fibra óptica simétrica de 100 Mbps, limpieza diaria y servicio de recepción. Torre Class A con acceso controlado y estacionamiento para 3 vehículos.",
  },
  {
    id: "53",
    title: "Finca turística eco-lodge — El Yuma",
    slug: "finca-eco-lodge-yuma",
    price: 890000,
    currency: "USD",
    type: "venta",
    category: "Finca",
    city: "El Yuma",
    zone: "Nacional",
    beds: 8,
    baths: 6,
    areaM2: 550,
    verified: true,
    featured: true,
    promo: true,
    image: getUnsplash("farm_1"),
    images: [
      getUnsplash("farm_1"),
      getUnsplash("farm_2"),
      getUnsplash("land_4"),
      getUnsplash("land_5"),
      getUnsplash("tropical_1"),
    ],
    lat: 18.3400,
    lng: -68.7200,
    amenities: ["pool", "garden", "parking", "security", "solar", "pet-friendly", "beach-access"],
    description:
      "Finca de 15 hectáreas adyacente al Parque Nacional del Este con casa principal de 550 m² y 8 cabañas independientes. Operación de eco-lodge certificada con ocupación del 72% anual. La casa principal tiene salón de eventos, restaurante, cocina industrial y área de administración. Biodiversidad protegida con más de 200 especies de aves documentadas.",
  },
  {
    id: "54",
    title: "Loft artístico — Galería de Arte Contemporáneo",
    slug: "loft-artistico-santo-domingo",
    price: 220000,
    currency: "USD",
    type: "venta",
    category: "Loft",
    city: "Santo Domingo",
    zone: "Zona de los Aristas",
    beds: 1,
    baths: 1,
    areaM2: 95,
    verified: true,
    featured: false,
    image: getUnsplash("loft"),
    images: [
      getUnsplash("loft"),
      getUnsplash("interior_4"),
      getUnsplash("interior_5"),
      getUnsplash("property_9"),
      getUnsplash("property_10"),
    ],
    lat: 18.4670,
    lng: -69.8900,
    amenities: ["terrace", "elevator", "security", "wifi", "balcony"],
    description:
      "Loft de 95 m² ubicado en el corazón del distrito artístico de Santo Domingo. Techos de 5 metros, paredes de ladrillo expuesto y ventanales industriales que dan a galerías de arte. Cocina modular de acero inoxidable, baño con ducha de lluvia Hansgrohe y terraza privada de 12 m². A pasos del Centro de Arte Contemporáneo Wenner Belisario.",
  },
  {
    id: "55",
    title: "Terreno con vista al mar — Punta Norte",
    slug: "terreno-punta-norte",
    price: 150000,
    currency: "USD",
    type: "venta",
    category: "Terreno",
    city: "Puerto Plata",
    zone: "Punta Norte",
    beds: 0,
    baths: 0,
    areaM2: 600,
    verified: true,
    featured: false,
    image: getUnsplash("land_1"),
    images: [
      getUnsplash("land_1"),
      getUnsplash("land_2"),
      getUnsplash("tropical_2"),
      getUnsplash("tropical_3"),
      getUnsplash("mountain_3"),
    ],
    lat: 19.8200,
    lng: -70.6500,
    amenities: ["ocean-view", "fence", "high-traffic"],
    description:
      "Terreno de 600 m² con vista panorámica al mar Caribe desde la cima de un acantilado de 40 metros. Acceso por camino de concreto, servicios eléctricos a 200 metros y agua municipal disponible. Permite construcción residencial de hasta 3 pisos. A 10 minutos de las mejores olas de Puerto Plata y del centro comercial Altos de Chavón.",
  },
  {
    id: "56",
    title: "Casa familiar con cine privado — Wadsworth",
    slug: "casa-wadsworth",
    price: 425000,
    currency: "USD",
    type: "venta",
    category: "Casa",
    city: "Santo Domingo",
    zone: "Wadsworth",
    beds: 5,
    baths: 4,
    areaM2: 320,
    verified: true,
    featured: false,
    image: getUnsplash("property_2"),
    images: [
      getUnsplash("property_2"),
      getUnsplash("property_3"),
      getUnsplash("luxury_int_4"),
      getUnsplash("luxury_int_5"),
      getUnsplash("interior_1"),
    ],
    lat: 18.4600,
    lng: -69.9500,
    amenities: ["pool", "garden", "parking", "security", "terrace", "ac"],
    description:
      "Residencia familiar de lujo con cine privado climatizado de 8 asientos. 320 m² con distribución generosa: sala formal, sala familiar con chimenea, comedor para 12, cocina gourmet con despensa doble. 5 suites, la principal con salón privado y jacuzzi. Piscina con escalera acuática, jardín paisajístico y estacionamiento techado para 4 vehículos.",
  },
  {
    id: "57",
    title: "Apartamento de lujo — The Residences at Cap Cana",
    slug: "apto-cap-cana-luxury",
    price: 950000,
    currency: "USD",
    type: "venta",
    category: "Apartamento",
    city: "Punta Cana",
    zone: "Cap Cana",
    beds: 3,
    baths: 3,
    areaM2: 200,
    verified: true,
    featured: true,
    promo: true,
    image: getUnsplash("property_3"),
    images: [
      getUnsplash("property_3"),
      getUnsplash("luxury_villa"),
      getUnsplash("condo_1"),
      getUnsplash("condo_2"),
      getUnsplash("luxury_int_1"),
    ],
    lat: 18.4950,
    lng: -68.4100,
    amenities: ["pool", "gym", "security", "ocean-view", "beach-access", "spa", "concierge", "parking"],
    description:
      "Residencia de lujo en los exclusivos The Residences at Cap Cana, con acceso a todas las amenidades del resort. 200 m² con vista al mar Caribe y al mar de la República Dominicana. Acabados importados de Italia y España, domótica Lutron, cocina Sub-Zero/Wolf. El desarrollo incluye playa privada, campo de golf Jack Nicklaus, marina y spa de clase mundial.",
  },
  {
    id: "58",
    title: "Local comercial en Plaza Central — Santiago",
    slug: "local-plaza-santiago",
    price: 3200,
    currency: "USD",
    type: "alquiler",
    category: "Local comercial",
    city: "Santiago",
    zone: "Centro",
    beds: 0,
    baths: 1,
    areaM2: 40,
    verified: true,
    featured: false,
    image: getUnsplash("commercial_3"),
    images: [
      getUnsplash("commercial_3"),
      getUnsplash("commercial_4"),
      getUnsplash("interior_5"),
      getUnsplash("property_7"),
      getUnsplash("property_9"),
    ],
    lat: 19.4500,
    lng: -70.7000,
    amenities: ["high-traffic", "security", "commercial-ready"],
    description:
      "Local comercial de 40 m² en el centro comercial más transitado de Santiago con 3 millones de visitantes anuales. Planta abierta con vitrina de 4 metros, iluminación LED y aire acondicionado. Ideal para tienda de ropa, accesorios o tecnología. El centro ofrece seguridad privada, estacionamiento subterráneo y eventos de marketing mensuales.",
  },
  {
    id: "59",
    title: "Villa neoclásica con parque privado — Santo Domingo",
    slug: "villa-neoclasica-sd",
    price: 1800000,
    currency: "USD",
    type: "venta",
    category: "Villa",
    city: "Santo Domingo",
    zone: "Naco",
    beds: 6,
    baths: 7,
    areaM2: 650,
    verified: true,
    featured: true,
    promo: true,
    image: getUnsplash("luxury_villa"),
    images: [
      getUnsplash("luxury_villa"),
      getUnsplash("estate_1"),
      getUnsplash("estate_2"),
      getUnsplash("luxury_int_2"),
      getUnsplash("luxury_int_4"),
    ],
    lat: 18.4660,
    lng: -69.9300,
    amenities: ["pool", "garden", "parking", "security", "terrace", "gym", "spa", "concierge"],
    description:
      "Villa neoclásica de arquitectura monumental en el exclusivo sector de Naco. 650 m² con 6 suites, sala de baile con piso de mármol italiano, biblioteca con estantería empotrada y bodega de vinos para 1,000 botellas. Piscina olímpica climatizada, gimnasio profesional, spa con sauna y hammam. Parque privado de 3,000 m² con cancha de tenis y jardín de esculturas.",
  },
  {
    id: "60",
    title: "Estudio minimalista — UASD Gazcue",
    slug: "estudio-uasd-gazcue",
    price: 18000,
    currency: "DOP",
    type: "alquiler",
    category: "Estudio",
    city: "Santo Domingo",
    zone: "Gazcue",
    beds: 0,
    baths: 1,
    areaM2: 28,
    verified: false,
    featured: false,
    image: getUnsplash("interior_5"),
    images: [
      getUnsplash("interior_5"),
      getUnsplash("interior_4"),
      getUnsplash("interior_3"),
      getUnsplash("interior_2"),
      getUnsplash("interior_1"),
    ],
    lat: 18.4720,
    lng: -69.9020,
    amenities: ["wifi", "ac", "furnished"],
    description:
      "Estudio minimalista de 28 m² ideal para estudiantes de la UASD. Amueblado con cama abatible, escritorio empotrado y cocina compacta. Edificio nuevo con ascensor, vigilancia y lavandería. A 3 minutos caminando del campus principal. Agua y luz incluidas.",
  },
  {
    id: "61",
    title: "Bodega logística — Zona Industrial de Nizao",
    slug: "bodega-nizao",
    price: 750000,
    currency: "USD",
    type: "venta",
    category: "Nave industrial",
    city: "Santo Domingo",
    zone: "Zona Industrial Nizao",
    beds: 0,
    baths: 2,
    areaM2: 2800,
    verified: true,
    featured: false,
    image: getUnsplash("warehouse_1"),
    images: [
      getUnsplash("warehouse_1"),
      getUnsplash("warehouse_2"),
      getUnsplash("commercial_4"),
      getUnsplash("commercial_1"),
      getUnsplash("commercial_2"),
    ],
    lat: 18.4300,
    lng: -69.9700,
    amenities: ["storage", "fence", "high-traffic", "parking", "commercial-ready"],
    description:
      "Bodega logística de 2,800 m² con 10 m de altura libre, 4 muelles de carga y sistema de sprinklers instalado. Piso de hormigón pulido de 15 cm de espesor para tráfico de montacargas. Oficina administrativa de 120 m², estacionamiento para 20 camiones y control de acceso con cámaras CCTV. Conectado a las tres autopistas principales.",
  },
  {
    id: "62",
    title: "Casa de playa con muelle privado — Bayahibe",
    slug: "casa-playa-bayahibe",
    price: 530000,
    currency: "USD",
    type: "venta",
    category: "Casa",
    city: "Bayahibe",
    zone: "Bahía de las Águilas",
    beds: 4,
    baths: 3,
    areaM2: 250,
    verified: true,
    featured: false,
    image: getUnsplash("beach_house"),
    images: [
      getUnsplash("beach_house"),
      getUnsplash("tropical_1"),
      getUnsplash("tropical_2"),
      getUnsplash("property_5"),
      getUnsplash("property_6"),
    ],
    lat: 18.1450,
    lng: -68.7750,
    amenities: ["pool", "garden", "parking", "security", "ocean-view", "beach-access"],
    description:
      "Casa de playa frente al mar con muelle privado para embarcaciones hasta 20 pies. 250 m² de arquitectura tropical contemporánea con terrazas perimetrales y piscina desbordante. 4 habitaciones con acceso directo a la playa, cocina abierta con isla y sistema de ventilación natural. Acceso directo a arrecife de coral para snorkeling.",
  },
  {
    id: "63",
    title: "Edificio de oficinas — Torre Global, Piantini",
    slug: "edificio-oficinas-global",
    price: 3500000,
    currency: "USD",
    type: "venta",
    category: "Edificio",
    city: "Santo Domingo",
    zone: "Piantini",
    beds: 0,
    baths: 0,
    areaM2: 2500,
    verified: true,
    featured: false,
    image: getUnsplash("office_1"),
    images: [
      getUnsplash("office_1"),
      getUnsplash("office_2"),
      getUnsplash("office_3"),
      getUnsplash("commercial_1"),
      getUnsplash("commercial_2"),
    ],
    lat: 18.4770,
    lng: -69.9230,
    amenities: ["elevator", "security", "parking", "coworking", "wifi", "concierge"],
    description:
      "Edificio de oficinas Class A de 8 pisos con 2,500 m² totales. Ocupación del 95% con contratos corporativos de 3-5 años. 48 ascensores, sistema HVAC central, data center en sótano y estacionamiento para 60 vehículos. Certificaciones LEED Gold y WELL Building. Ingreso anual por rentas de $420,000.",
  },
  {
    id: "64",
    title: "Villa con viñedo y bodega — Valle del Cibao",
    slug: "villa-vinedo-cibao-2",
    price: 680000,
    currency: "USD",
    type: "venta",
    category: "Villa",
    city: "San Francisco de Macorís",
    zone: "Valle Nuevo",
    beds: 5,
    baths: 5,
    areaM2: 400,
    verified: true,
    featured: false,
    image: getUnsplash("tropical_3"),
    images: [
      getUnsplash("tropical_3"),
      getUnsplash("farm_2"),
      getUnsplash("mountain_2"),
      getUnsplash("property_4"),
      getUnsplash("luxury_villa"),
    ],
    lat: 19.2200,
    lng: -70.0050,
    amenities: ["pool", "garden", "parking", "security", "terrace", "solar"],
    description:
      "Villa con viñedo de 5 hectáreas y bodega de producción artesanal de vino con capacidad de 10,000 litros. 400 m² de residencia principal con arquitectura rústica de lujo. 5 suites, sala de degustación con vista al valle, piscina infinity y cancha de padel. Producción de vino 'Zafra' con certificación de denominación de origen.",
  },
  {
    id: "65",
    title: "Penthouse con observatorio astronómico — Jarabacoa",
    slug: "penthouse-observatorio-jarabacoa",
    price: 480000,
    currency: "USD",
    type: "venta",
    category: "Penthouse",
    city: "Jarabacoa",
    zone: "Cerro de la Salle",
    beds: 3,
    baths: 3,
    areaM2: 260,
    verified: true,
    featured: false,
    image: getUnsplash("mountain_3"),
    images: [
      getUnsplash("mountain_3"),
      getUnsplash("mountain_1"),
      getUnsplash("luxury_int_5"),
      getUnsplash("property_1"),
      getUnsplash("property_2"),
    ],
    lat: 19.1350,
    lng: -70.6300,
    amenities: ["pool", "gym", "terrace", "security", "elevator", "spa", "solar"],
    description:
      "Penthouse único con observatorio astronómico funcional en la azotea. 260 m² a 1,200 msnm con vistas de 180° al valle central. 3 suites con chimenea, cocina con isla en cuarzo y sistema geotérmico de climatización. Telescopio profesional Celestron montado en domo rotatorio. Piscina infinita con vista a las montañas.",
  },
  {
    id: "66",
    title: "Townhouse con jardín zen — Los Próceres",
    slug: "townhouse-proceres",
    price: 195000,
    currency: "USD",
    type: "venta",
    category: "Townhouse",
    city: "Santo Domingo",
    zone: "Los Próceres",
    beds: 3,
    baths: 2,
    areaM2: 145,
    verified: true,
    featured: false,
    image: getUnsplash("garden_view_1"),
    images: [
      getUnsplash("garden_view_1"),
      getUnsplash("garden_view_2"),
      getUnsplash("property_8"),
      getUnsplash("property_9"),
      getUnsplash("interior_2"),
    ],
    lat: 18.4500,
    lng: -69.9550,
    amenities: ["parking", "garden", "security", "pet-friendly", "storage"],
    description:
      "Townhouse con jardín zen japonés diseñado por paisajista premiada. 145 m² en urbanización de acceso controlado. 3 habitaciones, 2 baños, cocina con isla y comedor para 6. Patio interior con fuente de piedra, bambú y piedras de río. Estacionamiento techado y bodega individual.",
  },
  {
    id: "67",
    title: "Local gastronómico — Malecón, Santo Domingo",
    slug: "local-malecon-sd",
    price: 9500,
    currency: "USD",
    type: "alquiler",
    category: "Local comercial",
    city: "Santo Domingo",
    zone: "Malecón",
    beds: 0,
    baths: 2,
    areaM2: 120,
    verified: true,
    featured: false,
    image: getUnsplash("hotel_2"),
    images: [
      getUnsplash("hotel_2"),
      getUnsplash("commercial_2"),
      getUnsplash("commercial_3"),
      getUnsplash("interior_5"),
      getUnsplash("property_7"),
    ],
    lat: 18.4610,
    lng: -69.8950,
    amenities: ["high-traffic", "terrace", "commercial-ready", "storage"],
    description:
      "Local gastronómico de 120 m² con terraza de 40 m² frente al Malecón 21 de Septiembre. Listo para restaurante o bar: incluye extracción de humos industrial, lavandería, baño comercial y conexión de gas. Afluencia de 25,000 personas diarias. Contrato de 5 años con opción a renovación.",
  },
  {
    id: "68",
    title: "Finca avícola — San Cristóbal",
    slug: "finca-avicola-san-cristobal",
    price: 320000,
    currency: "USD",
    type: "venta",
    category: "Finca",
    city: "San Cristóbal",
    zone: "Industria",
    beds: 2,
    baths: 1,
    areaM2: 200,
    verified: true,
    featured: false,
    image: getUnsplash("land_4"),
    images: [
      getUnsplash("land_4"),
      getUnsplash("land_5"),
      getUnsplash("farm_1"),
      getUnsplash("farm_2"),
      getUnsplash("garden_1"),
    ],
    lat: 18.4100,
    lng: -70.0200,
    amenities: ["storage", "parking", "fence"],
    description:
      "Finca avícola operativa de 10 hectáreas con 3 galpones climatizados y capacidad para 30,000 aves. Casa principal de 200 m² con 2 habitaciones, oficina, laboratorio de vacunación y bodega de alimentos. Sistema de generación de energía solar para reducción de costos eléctricos. Contrato de suministro con empresa avícola líder.",
  },
  {
    id: "69",
    title: "Residencia con cancha de pádel — Naco",
    slug: "residencia-padel-naco",
    price: 520000,
    currency: "USD",
    type: "venta",
    category: "Casa",
    city: "Santo Domingo",
    zone: "Naco",
    beds: 4,
    baths: 4,
    areaM2: 300,
    verified: true,
    featured: false,
    image: getUnsplash("property_4"),
    images: [
      getUnsplash("property_4"),
      getUnsplash("luxury_villa"),
      getUnsplash("property_3"),
      getUnsplash("modern_house_2"),
      getUnsplash("loft"),
    ],
    lat: 18.4640,
    lng: -69.9320,
    amenities: ["pool", "garden", "parking", "security", "terrace", "gym"],
    description:
      "Residencia moderna con cancha de pádel reglamentaria privada. 300 m² con diseño arquitectónico de autor. 4 suites, gimnasio privado con equipo Technogym, cocina Smeg con isla en mármol y piscina de inmersión terapéutica. Sistema domótico completo con control de iluminación, climatización y seguridad desde smartphone.",
  },
  {
    id: "70",
    title: "Apartamento de lujo — The Royal Tower, Punta Cana",
    slug: "apto-royal-tower-punta-cana",
    price: 1100000,
    currency: "USD",
    type: "venta",
    category: "Apartamento",
    city: "Punta Cana",
    zone: "Uvero Alto",
    beds: 4,
    baths: 4,
    areaM2: 280,
    verified: true,
    featured: true,
    promo: true,
    image: getUnsplash("condo_1"),
    images: [
      getUnsplash("condo_1"),
      getUnsplash("condo_2"),
      getUnsplash("condo_3"),
      getUnsplash("luxury_int_1"),
      getUnsplash("luxury_int_3"),
    ],
    lat: 18.6800,
    lng: -68.4300,
    amenities: ["pool", "gym", "terrace", "security", "elevator", "spa", "concierge", "ocean-view", "parking"],
    description:
      "Apartamento de lujo en la torre residencial más alta de Punta Cana con vista 360° al mar Caribe y las montañas del norte. 280 m² con acabados de primera calidad, terraza amueblada de 50 m² y acceso a todas las amenidades del resort: playa privada, spa, campo de golf y marina. Inversión con programa de rental management y retorno del 8% anual.",
  },
];

export function getPromotionalProperties(): Property[] {
  return MOCK_PROPERTIES.filter((p) => p.promo === true);
}

export function getPropertyById(id: string): Property | undefined {
  return MOCK_PROPERTIES.find((p) => p.id === id);
}

export function getSimilarProperties(
  current: Property,
  limit = 3
): Property[] {
  const sameCity = MOCK_PROPERTIES.filter(
    (p) => p.id !== current.id && p.city === current.city
  );
  if (sameCity.length >= limit) return sameCity.slice(0, limit);
  const sameCategory = MOCK_PROPERTIES.filter(
    (p) =>
      p.id !== current.id &&
      p.category === current.category &&
      !sameCity.some((s) => s.id === p.id)
  );
  return [...sameCity, ...sameCategory].slice(0, limit);
}